### ISSUE TITLE
大佬您好 请问这是什么原因啊

### ISSUE THREAD

**Issue by dezexi** [lonsty/auto-login-qqmusic#2]
DevTools listening on ws://127.0.0.1:1784/devtools/browser/e0d7b165-2e3c-4003-8bed-653ab00de368
[64380:63800:0325/214148.061:ERROR:device_event_log_impl.cc(214)] [21:41:48.062] USB: usb_device_handle_win.cc:1056 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)
[64380:63800:0325/214148.073:ERROR:device_event_log_impl.cc(214)] [21:41:48.074] USB: usb_device_handle_win.cc:1056 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)
Cookies set successfully at Thu Mar 25 21:41:50 2021

**Comment by lonsty** [comment]
是在什么机器上运行的？

> Cookies set successfully at Thu Mar 25 21:41:50 2021

看结果又是成功的。有验证过有没有设置 cookie 成功吗？

> device_event_log_impl.cc(214)] [21:41:48.062] USB: usb_device_handle_win.cc:1056

像是 chromedriver 要 读取什么 USB 设备。

**Comment by dezexi** [comment]
发送过去了 但是cookie是无效的 好像是 webusb什么的

**Comment by dezexi** [comment]
> 发送过去了 但是cookie是无效的 好像是 webusb什么的

在win10 上运行 一开始没有提示的 后面就有这个提示 但是能收到cookie，但但是cookie 无效

**Comment by dezexi** [comment]
对了 我从4. 开启定时任务 这一步开始就没使用了!我用了系统的任务计划，写了一个bat脚本
@echo off
start cmd /k "cd/d E:\GitHub\qqmusic-cookie-setter &&python qqmusic_cookie_setter.py" 
TIMEOUT /T 120
taskkill /f /im cmd.exe

**Comment by dezexi** [comment]
我安装的是Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
使用git bash here运行python qqmusic_cookie_setter.py 时没有错误提示
使用powreshell和cmd则会出现提示
DevTools listening on ws://127.0.0.1:1784/devtools/browser/e0d7b165-2e3c-4003-8bed-653ab00de368
[64380:63800:0325/214148.061:ERROR:device_event_log_impl.cc(214)] [21:41:48.062] USB: usb_device_handle_win.cc:1056 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)
Cookies set successfully at Thu Mar 25 21:41:50 2021

**Comment by lonsty** [comment]
运行的时候能看到自动打开网页，输入帐密完成登录吗？

这个工具还不完整，处理不了滑块验证。

**Comment by dezexi** [comment]
> 运行的时候能看到自动打开网页，输入帐密完成登录吗？
> 
> 这个工具还不完整，处理不了滑块验证。

可以的，能看到QQ提示使用账号登录了音乐，昨天频繁登录，需要验证滑块，这个滑块是还不能自动处理。

**Comment by dezexi** [comment]
{"result":100,"data":{"cookie":{"path_tmp":"","uin":""},"userCookie":{"psrf_qqaccess_token":"78435F934B71586B497E59E11C105330","psrf_access_token_expiresAt":"1624496421","uin":"1004273358","psrf_qqrefresh_token":"7B7068C2346611590E4D1C8FA3A7C645","tmeLoginType":"2","psrf_qqopenid":"64B102652E3D32CEC288884A8F509D48","ptcz":"0e2874231e37c0829f920db8e711f481951d928ef655d7120b2b3d77e2125301","qm_keyst":"Q_H_L_2KYCT160eed1VvCcIKQRfcZ-gtf1VrTx83r-NLZ9vsSFohJnRapcuOfY0cR4_K2","ts_uid":"1361311533","ptui_loginuin":"1004273358","pgv_pvid":"2263965477","ts_last":"y.qq.com/","psrf_musickey_createtime":"1616720421","psrf_qqunionid":"","euin":"oKnz7e-loiokNn**","qqmusic_key":"Q_H_L_2KYCT160eed1VvCcIKQRfcZ-gtf1VrTx83r-NLZ9vsSFohJnRapcuOfY0cR4_K2","pgv_info":"ssid","_qpsvr_localtk":"0.29279623174776215","RK":"7Z6cfKd/Wb","yqq_stat":"0"}}}

**Comment by dezexi** [comment]
> {"result":100,"data":{"cookie":{"path_tmp":"","uin":""},"userCookie":{"psrf_qqaccess_token":"78435F934B71586B497E59E11C105330","psrf_access_token_expiresAt":"1624496421","uin":"1004273358","psrf_qqrefresh_token":"7B7068C2346611590E4D1C8FA3A7C645","tmeLoginType":"2","psrf_qqopenid":"64B102652E3D32CEC288884A8F509D48","ptcz":"0e2874231e37c0829f920db8e711f481951d928ef655d7120b2b3d77e2125301","qm_keyst":"Q_H_L_2KYCT160eed1VvCcIKQRfcZ-gtf1VrTx83r-NLZ9vsSFohJnRapcuOfY0cR4_K2","ts_uid":"1361311533","ptui_loginuin":"1004273358","pgv_pvid":"2263965477","ts_last":"y.qq.com/","psrf_musickey_createtime":"1616720421","psrf_qqunionid":"","euin":"oKnz7e-loiokNn**","qqmusic_key":"Q_H_L_2KYCT160eed1VvCcIKQRfcZ-gtf1VrTx83r-NLZ9vsSFohJnRapcuOfY0cR4_K2","pgv_info":"ssid","_qpsvr_localtk":"0.29279623174776215","RK":"7Z6cfKd/Wb","yqq_stat":"0"}}}

这串cookie是自动获取上传的，但是无效果，是不是格式或者哪里不对呢

**Comment by lonsty** [comment]
如果 qqmusic_cookie_setter.py 能获取到 cookie，那说明已经登录成功了。

你可以手动登录 qq 音乐，复制 cookie，用 postman 发送给 API，验证是否生效。我不知道 QQMusicAPI 有没有更新

**Comment by dezexi** [comment]
> 如果 qqmusic_cookie_setter.py 能获取到 cookie，那说明已经登录成功了。
> 
> 你可以手动登录 qq 音乐，复制 cookie，用 postman 发送给 API，验证是否生效。我不知道 QQMusicAPI 有没有更新

好的非常感谢大佬的回复！请问大佬有没有蕉流群啊？

**Comment by lonsty** [comment]
哈，没有交流群，没啥技术含量。好奇你是怎么找到这个仓库的？
